### ISSUE TITLE
Array phase

### ISSUE THREAD

**Issue by MicJ70** [hgiddenss/CST_App#3]
Hi! Thanks for your code: it's amazing!!! 
I've a question for you: my design is an array of 4 dipole, how is it possible to set the simultaneous excitation of the 4 ports and set a different phase for each of them? 
Thank you ;)

**Comment by hgiddenss** [comment]
Hi @MicJ70, 
Sorry for such a late response! Are you still wondering about this issue? If so I will have a look for you

**Comment by MicJ70** [comment]
Hi,

yes I'm still working on it! Why? are you working on the same issue?

Best,

Michela
________________________________
Da: Henry Giddens ***@***.***>
Inviato: mercoledì 5 ottobre 2022 11:31
A: hgiddenss/CST_App ***@***.***>
Cc: Michela Longhi ***@***.***>; Mention ***@***.***>
Oggetto: Re: [hgiddenss/CST_App] Array phase (Issue #3)


Hi @MicJ70<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicJ70&data=05%7C01%7C%7Ca90d6b19b06e46ba051308daa6b4686f%7Cffb4df68f464458ca54600fb3af66f6a%7C0%7C0%7C638005591023797143%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=zhKcnacQA8lWeNGxe7OKGN68XuwrsuBL6s%2BEsC9Fsms%3D&reserved=0>,
Sorry for such a late response! Are you still wondering about this issue? If so I will have a look for you

**Comment by hgiddenss** [comment]
Hi @MicJ70 

Sorry for the delay as I have been busy with other work. I have finally found a way of implementing this. You can run the example below. Let me know if it is useful or you find any other bugs (very likely). Note that you should enter values for ports (portnumber), phase, ampliute, and status for all ports in the simulation. You can turn certain ports off by setting the status or amplitude to 0.

```
CST = CST_MicrowaveStudio(cd,'multiPort.cst')
CST.setFreq(0, 3);
CST.addDiscretePort([-15.614 -15.614],[-15.614 -15.614],[0 62.5],0,73) %port 1
CST.addDiscretePort([-15.614 -15.614],[15.614 15.614],[0 62.5],0,73) %port 2
CST.addDiscretePort([15.614 15.614],[15.614 15.614],[0 62.5],0,73) %port 3
CST.addDiscretePort([15.614 15.614],[-15.614 -15.614],[0 62.5],0,73) %port 4
ports = [1 2 3 4];
phase = [0 -90 0 90];
amplitude = [1 1 1 1];
status = [1 1 1 1]; % turn all ports on
CST.setSimultaneousPortExcitation(ports,amplitude,phase,status,2.4,'simultaneous_excitation_2.4GHz')
CST.addFieldMonitor('farfield',2.4)
CST.addFieldMonitor('efield',2.4)
CST.runSimulation;
```

**Comment by MicJ70** [comment]
Hi Henry,

Thank you for your answer. But now the problem is that Matlab is not able to write on the CST History List, is it the same for you? I can't understand which is the problem, maybe the CST version?

Have a nice day,
Michela
________________________________
Da: Henry Giddens ***@***.***>
Inviato: Monday, December 19, 2022 9:49:15 AM
A: hgiddenss/CST_App ***@***.***>
Cc: Michela Longhi ***@***.***>; Mention ***@***.***>
Oggetto: Re: [hgiddenss/CST_App] Array phase (Issue #3)


Closed #3<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fhgiddenss%2FCST_App%2Fissues%2F3&data=05%7C01%7C%7Cc56519a0a9964999393408dae19de9aa%7Cffb4df68f464458ca54600fb3af66f6a%7C0%7C0%7C638070365598628932%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=YDZcO3h9FWztab7%2Fz6uE1kOzXPpG1eYrYK5pIzXoy4w%3D&reserved=0> as completed.

**Comment by hgiddenss** [comment]
Hi Michaela,

No I don't appear to be having any issues and I can run the code above and all seems to be correct. Which part is not writing to the history list?

**Comment by MicJ70** [comment]
All parts, the history list is completely empty.
________________________________
Da: Henry Giddens ***@***.***>
Inviato: Monday, December 19, 2022 10:01:49 AM
A: hgiddenss/CST_App ***@***.***>
Cc: Michela Longhi ***@***.***>; Mention ***@***.***>
Oggetto: Re: [hgiddenss/CST_App] Array phase (Issue #3)


Hi Michaela,

No I don't appear to be having any issues and I can run the code above and all seems to be correct. Which part is not writing to the history list?

**Comment by hgiddenss** [comment]
Hi Michaela,

There is an option in the CST_App that allows history list to either be updated all at once or as each command is executed (when running long scripts adding lots of components to the model, this can speed up the time it takes by a factor of 2-3). 

This can be turned on with: 
`CST.setUpdateStatus = true;`

and off with
`CST.setUpdateStatus = false;`

If you have it turned on then you must execute the command `CST.addToHistory` once you have finished all the steps in your code. Perhaps this is the problem?

Try running this? has it worked?
```
CST = CST_MicrowaveStudio(cd,'multiPort.cst')
CST = CST.setUpdateStatus = false;
CST.setFreq(0, 3);
CST.addDiscretePort([-15.614 -15.614],[-15.614 -15.614],[0 62.5],0,73) %port 1
CST.addDiscretePort([-15.614 -15.614],[15.614 15.614],[0 62.5],0,73) %port 2
CST.addDiscretePort([15.614 15.614],[15.614 15.614],[0 62.5],0,73) %port 3
CST.addDiscretePort([15.614 15.614],[-15.614 -15.614],[0 62.5],0,73) %port 4
ports = [1 2 3 4];
phase = [0 -90 0 90];
amplitude = [1 1 1 1];
status = [1 1 1 1]; % turn all ports on
CST.setSimultaneousPortExcitation(ports,amplitude,phase,status,2.4,'simultaneous_excitation_2.4GHz')
CST.addFieldMonitor('farfield',2.4)
CST.addFieldMonitor('efield',2.4)
CST.addToHistory; %Just in case...
CST.runSimulation;
```

**Comment by MicJ70** [comment]
Hi Henry,

It doesn't work, the Matlab answer is:

"Unrecognized method, property, or field 'setUpdateStatus' for class 'TSCTInterface'.

How is it possible?
M
________________________________
Da: Henry Giddens ***@***.***>
Inviato: lunedì 19 dicembre 2022 10:21
A: hgiddenss/CST_App ***@***.***>
Cc: Michela Longhi ***@***.***>; Mention ***@***.***>
Oggetto: Re: [hgiddenss/CST_App] Array phase (Issue #3)


Hi Michaela,

There is an option in the CST_App that allows history list to either be updated all at once or as each command is executed (when running long scripts adding lots of components to the model, this can speed up the time it takes by a factor of 2-3).

This can be turned on with:
CST.setUpdateStatus = true;

and off with
CST.setUpdateStatus = false;

If you have it turned on then you must execute the command CST.addToHistory once you have finished all the steps in your code. Perhaps this is the problem?

Try running this? has it worked?

CST = CST_MicrowaveStudio(cd,'multiPort.cst')
CST = CST.setUpdateStatus = false;
CST.setFreq(0, 3);
CST.addDiscretePort([-15.614 -15.614],[-15.614 -15.614],[0 62.5],0,73) %port 1
CST.addDiscretePort([-15.614 -15.614],[15.614 15.614],[0 62.5],0,73) %port 2
CST.addDiscretePort([15.614 15.614],[15.614 15.614],[0 62.5],0,73) %port 3
CST.addDiscretePort([15.614 15.614],[-15.614 -15.614],[0 62.5],0,73) %port 4
ports = [1 2 3 4];
phase = [0 -90 0 90];
amplitude = [1 1 1 1];
status = [1 1 1 1]; % turn all ports on
CST.setSimultaneousPortExcitation(ports,amplitude,phase,status,2.4,'simultaneous_excitation_2.4GHz')
CST.addFieldMonitor('farfield',2.4)
CST.addFieldMonitor('efield',2.4)
CST.addToHistory; %Just in case...
CST.runSimulation;

**Comment by hgiddenss** [comment]
Hi 

It sounds like you are running some different code. TCSTInterface is a similar CST/Matlab API  from this repositry https://github.com/korvin011/CSTMWS-Matlab-Interface 

Maybe you have your paths/variables mixed up and it is causing you some problems?
