### ISSUE TITLE
Change Material of created Brick

### ISSUE THREAD

**Issue by c8501024** [hgiddenss/CST_App#4]
First of all -> thank you very much for this matlab class!
My question is, if it is somehow possible to change the material of a brick by the name of the brick? 
So if i have a Brick with the name 129 and it has material copper i want to set it do lets say vacuum.

**Comment by c8501024** [comment]
I searched through the VBA documentation for CST and I created following function: 

```
function changeSolidMaterial(obj,componentname,solidname,materialname)
            VBA=sprintf('solid.ChangeMaterial "%s:%s", "%s"', componentname,solidname,materialname);
            obj.update(['change material of brick: ',componentname,':',solidname,' to ',materialname],VBA);
end
```
This function copied into "CST_MicrowaveStudio.m" adds this functionality.

Is it possible to be part of your development team on github?

**Comment by hgiddenss** [comment]
Hi @c8501024 
Sorry I have only just seen this comment. Yes I am open for collaborations if you are interested.
