### ISSUE TITLE
frequency domain solver

### ISSUE THREAD

**Issue by Sarvesh178** [hgiddenss/CST_App#5]
hello sir ,
for different frequency range i am getting different number of samples even though i am giving 1001 samples as my limit............

so according to that why am i getting more than 1001 samples while exporting by plot ascii data

what changes i should incorporate so that i should get always 1001 data

plz do reply sir

**Comment by hgiddenss** [comment]
Hi @Sarvesh178 
Sorry for the late reply but if you are still having trouble this may help.
You are able to read the s-parameter data straight into MATLAB using the function
`[freq,sparam,sparamType] = CST.getSParams('s11')`
If this is returning different number of frequency points, then you could resample the data using interp1 e.g:
```
[freq_CST,s11] = getSParams('s11')
freq = linspace(freq_CST(1),freq_cst(end),1001)
s11_resampled = interp1(freq_CST,s11,freq);
figure;
plot(freq,s11_resampled)
```
