### ISSUE TITLE
Invalid character code sequence detected.

### ISSUE THREAD

**Issue by Zevgas007** [hgiddenss/CST_App#8]
Hello. I am trying to run the example code of the MetaSurface and I get a message that says << Invalid character code sequence detected  >> .
 I have trace the problem in the CST_MicrowaveStudio.m in the Function that sets the units and fixed it but I still have the same issue. 
I think it has something to do with the addToHistory function but I can't find it. 
I am using 2023 version o CST and 2024a matlab I think the problem is with the cst newer version But I don't know how to fix it !!! Thank you

**Comment by SamDu1998** [comment]
Please use Matlab R2023b or lower version. I meet that problem too, and solved that one by downgrade the matlab version.

**Comment by Zevgas007** [comment]
Does the version of CST matter ??

**Comment by Zevgas007** [comment]
I got it to work thanks !!!
